name = "tma"
main = "./src/server.js"
compatibility_date="2022-02-26"

account_id = "0310df0fd9a2a832b38ae5f648543181"
workers_dev = true

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]

[env.dev]

[env.production]

# [secrets]
# TMA_DISCORD_TOKEN
# TMA_DISCORD_PUBLIC_KEY
# TMA_DISCORD_APPLICATION_ID
# TMA_DISCORD_TEST_GUILD_ID
